### ISSUE TITLE
Exeption not handled?

### ISSUE THREAD

**Issue by joelcnz** [TheWeirdDev/Calcool#1]
I put the code in try..catch(Exeption e), but get this error:
calcool.exceptions.ParseException@../../OtherPeoples/calcoolLib/exceptions.d(6): Expected token of type PR_OPEN

**Comment by joelcnz** [comment]
Oh, I didn't have a try catch block, sorry..

**Comment by TheWeirdDev** [comment]
Good thing you mentioned exceptions, i remembered something.
I used exceptions for control flow and now i kinda regret it. I made a few small changes to make it a bit better. for now every `CalcoolException` and `Exception` should be treated as an error but `EndException`s should be ignored 🤦‍♂️.
