### ISSUE TITLE
Library?

### ISSUE THREAD

**Issue by joelcnz** [TheWeirdDev/Calcool#2]
Why not make it a library?

**Comment by TheWeirdDev** [comment]
I wrote the whole thing with CLI app in mind and now making it a library will need some changes. Maybe we could take advantage of D's `version` condition to make two versions. One for the app and one for the library. I'm not really familiar with it though.

**Comment by joelcnz** [comment]
I noticed there’s already a expression library - have you seen that?

**Comment by TheWeirdDev** [comment]
Yes i have

**Comment by TheWeirdDev** [comment]
I just added support for a library version of Calcool. Read the Readme.md file.
